### Este archivo contiene los endpoints iniciales para poder comenzar a usar la api

### para encriptar el mensaje
POST http://localhost:3000/api/message/encrypt
Content-Type: application/json

{
    "message":"gael es puto",
    "question":"definicion de gael",
    "secret":"secretKey"
}

### para desencriptar el mensaje
POST http://localhost:3000/api/message/desencrypt
Content-Type: application/json

{
    "id":"el id del mensaje",
    "secret":"el secreto que esta dando la persona para descrifrar el mensaje"
}

### para iniciar sesion

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "name":"el nombre de usuario",
    "password":"la contraseña"
}

### para registrar un nuevo usuario

POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "name":"el nombre de usuario",
    "email":"el correo electronico",
    "password":"la contraseña"
    
}

### consultar mensajes encriptados
GET http://localhost:3000/api/message
